//! `RequestCacheDescriptor` -- compile-time metadata for a `#[request_cache]`
//! resolver.
//!
//! A sibling to `AuthUser`: this is the *compile-time* contract the
//! `#[request_cache]` proc-macro generates against. This descriptor is pure
//! data -- a `&'static` const aggregated into the Unified Application Graph
//! by `arcature-build` so the Inspector, `arc check`, and the MCP
//! `system_checks` tool can show per-request memoized resolvers without
//! running the application.
//!
//! # No runtime here
//!
//! This module carries NO runtime behavior -- no `RequestCache`, no
//! memoization, no locking. It is metadata only, matching the one-file-one-
//! responsibility law: the descriptor (this file) is separate from any
//! runtime container. A small app that enables `dx` gets the descriptor (so
//! the UAG can record declared resolvers) without a runtime cache.
//!
//! # Example
//!
//! ```ignore
//! // Generated by `#[request_cache]` in arcature-macros:
//! pub const LOAD_PROFILE_REQUEST_CACHE: ::arcature::RequestCacheDescriptor =
//!     ::arcature::RequestCacheDescriptor {
//!         name: "load_profile",
//!         key_fields: &["user_id"],
//!     };
//! ```

/// Compile-time metadata for a per-request memoized resolver.
///
/// The `#[request_cache]` proc-macro generates a `pub const <NAME>_REQUEST_CACHE:
/// RequestCacheDescriptor` for each annotated resolver. The descriptor records
/// the resolver's name and the names of the parameters that form its cache key,
/// so the UAG / Inspector can show "this resolver is memoized per request by
/// `<key_fields>`" without running the resolver.
///
/// The fields are `&'static` so the descriptor is `const`-constructible and
/// lives in the binary (no allocation). A descriptor is *declarative* -- it
/// does not cause memoization. The descriptor is what the graph records.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
pub struct RequestCacheDescriptor {
    /// The resolver's name (typically the function name).
    pub name: &'static str,
    /// The names of the parameters that form the cache key, in declaration
    /// order. A single-field key is the common case; a composite key lists
    /// each constituent field name.
    pub key_fields: &'static [&'static str],
}
