[package]
name = "__RUST_NAME__"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[dependencies]
arcature = { version = "__ARCATURE_VERSION__", features = ["macros", "inertia", "database", "auth", "validation", "cache", "storage-fs", "mail", "jobs", "events", "api", "observe", "pages", "realtime", "cli", "templates"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15"
async-trait = "0.1"

[lib]
path = "src/lib.rs"

[[bin]]
name = "__RUST_NAME__"
path = "src/main.rs"
